<h4>Options</h4> 
<div class="table-responsive">
	<table width="100%" class="table table-striped table-bordered table-hover" id="vue-table1-table1">
		<thead><tr>
		  <th>名称</th><th>备注</th><th>默认</th><th>源码</th><th>示例</th>
		</tr></thead>
		<tbody>
		  <tr>
		    <th>JZ.Table</th>
		    <td>加载一个单独的数据表格</td>
		    <td>✔</td>
			<th><a target="_blank" href="https://github.com/tlianglstyle/JZUI/blob/master/src/js/app/JZ/Table.js">...</a></th>
			<th><a target="_blank" href="http://tlianglstyle.github.io/JZUI/dist/app/Table/Table.html">...</a></th>
		  </tr>
		  <tr>
		    <th>JZ.Vue</th>
		    <td>加载一个继承自vue.js的全局Vue工具集</td>
		    <td>✔</td>
			<th><a target="_blank" href="https://github.com/tlianglstyle/JZUI/blob/master/src/js/app/JZ/VueInit.js">...</a></th>
			<th><a target="_blank" href="http://tlianglstyle.github.io/JZUI/dist/app/Vue/index.html">...</a></th>
		  </tr>
		  <tr>
		    <th>JZ.Form</th>
		    <td>初始化一个包含验证和提交功能的表单</td>
		    <td>✔</td>
			<th><a target="_blank" href="https://github.com/tlianglstyle/JZUI/blob/master/src/js/app/JZ/Form.js">...</a></th>
			<th><a target="_blank" href="http://tlianglstyle.github.io/JZUI/dist/app/Form/index.html">...</a></th>
		  </tr>
		</tbody>
	</table>
	<a class="alert-link" target="_blank" href="https://github.com/tlianglstyle/JZUI/tree/master/src/js/app/JZ">在Github上查看源码</a>
</div> 
		 