<h3>JZ.js是什么</h3>
<p><code>JZ.js</code>是基于<code>bootstrap</code>，<code>vuejs</code>和<code>jquery，</code>配合<code>webpack</code>,<code>gulp</code>构建工具搭建的后端js组件库，主要用于web管理界面等网站。</p>

<h3>为什么叫JZ.js</h3>
<p>此项目需求源自于作者所在公司内部使用，各位同学如有房屋装修需求可来我司体验间体验一番：<br>
网址：<a class="alert-link" target="_blank" href="http://www.jzjz.com">www.jzjz.com</a><br>
体验间地址：北京市 海淀区 紫竹院街道	北洼路苏宁易购三层极装吉住。
</p>

<h3>JZ.js的由来</h3>
<p>用过了Extjs，Jquery UI/EasyUI ，AngularJS等js库的同学可能会都有这样的苦恼：</p>
<p>
1.虽然提供了丰富的API，但并未开放源代码，且难以调试；<br>
2.虽然各种各样的接口和参数设置，但有时仍然无法满足特定的开发需求；<br>
3.html，css模块进行了深度整合，无法更好的自定义html标签和css样式；<br>
...
</p>
<p>所以我们在一些后端项目开发中遇到了以上的问题，开发了JZ.js。</p>
<h3>JZ.js的特点</h3>
<p>
1.使用通用的bootstrap作为UI层，你可以自由的更换自己专属的boostrap作为UI层；<br><a class="alert-link" target="_blank" href="http://v3.bootcss.com/customize/">定制并下载 Bootstrap</a><br>
2.使用语法较为简洁的vuejs实现数据驱动，除了使用JZ.js提供的组件之外，你还可以自由使用vuejs的其他功能(如单向、双向数据绑定等)。<br><a class="alert-link" target="_blank" href="http://tlianglstyle.github.io/JZUI/dist/app/Table/Search.html">查看示例</a><br>
3.开放<a class="alert-link" target="_blank" href="https://github.com/tlianglstyle/JZUI">所有源码(以及这几个简单的介绍页)</a>，根据你的需求，可以下载并修改代码成为自己的工具集。<br>

</p>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  使用vuejs时我们需要很多数组操作，并同时整理了一些常用的<a class="alert-link" target="_blank" href="https://github.com/tlianglstyle/JZUI/blob/master/src/js/app/JZ/Array.js">数组操作函数</a>；<br><a class="alert-link" target="_blank" href="http://tlianglstyle.github.io/JZUI/dist/app/Table/TableSelects.html">查看示例</a>
</div>
 