<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<!-- Core -->
<link href="../../../src/local_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Menu -->
<link href="../../../src/js/lib/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
 
<!-- Fonts -->
<link href="../../../src/local_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> 

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]--> 
<script src="../../../src/local_modules/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="../../../src/local_modules/vue/dist/vue.js" type="text/javascript"></script>
<script src="../../../src/local_modules/bootstrap/dist/js/bootstrap.js" type="text/javascript"></script>
<script src="../../../src/js/lib/metisMenu/dist/metisMenu.min.js" type="text/javascript"></script>
<script src="../../../src/js/lib/tools/validate/jquery.validate.min.js"></script> 
<script src="../../../src/js/lib/tools/validate/additional-methods.js"></script>
<script src="../../../src/js/lib/tools/validate/messages_zh.js"></script>
<script src="../../../src/js/lib/tools/validate/validate-methods.js"></script>
<script src="../../../src/js/lib/sb-admin-2.js"></script> 
<script src="../../../src/js/lib/tools/WdatePicker/WdatePicker.js"></script>
<script src="../../../src/js/lib/tools/bootbox.js"></script>
<link href="../../../src/js/utils/prettify/prettify.min.css" rel="stylesheet" type="text/css" />
 
<link href="../../../src/js/lib/tools/lightbox/css/lightbox.min.css" rel="stylesheet" type="text/css" />
<script src="../../../src/js/lib/tools/lightbox/js/lightbox.min.js"></script> 



<link href="../../../src/js/lib/tools/zTree/zTreeStyle.css" rel="stylesheet" type="text/css" />
<script src="../../../src/js/lib/tools/zTree/jquery.ztree.all.min.js"></script> 

<script src="../../../src/js/utils/prettify/prettify.js"></script>

<script>var Ctx = ctx = '',ENV_JZ = 'dev';</script>
<link href="../../../src/css/common/JZ.css" rel="stylesheet" type="text/css" />
<script src="../../../dist/js/app/JZ/JZ.js"></script>